const API_BASE_URL = window.APP_CONFIG?.API_BASE_URL ?? "http://localhost:8081";
const status = document.getElementById("dashboard-status");
const content = document.getElementById("dashboard-content");
const yen = value => `¥${Number(value || 0).toLocaleString("ja-JP")}`;
const safe = value => value == null || value === "" ? "—" : String(value);
function renderKpis(d) { document.getElementById("kpis").innerHTML = [["今月の支出合計",yen(d.currentMonthTotal),"今月"],["今月のレシート数",`${d.currentMonthReceiptCount} 件`,d.period],["平均支出／日",yen(d.averagePerDay),"経過日数ベース"],["登録レシート総数",`${d.totalReceiptCount} 件`,"全期間"]].map(x=>`<article class="kpi-card"><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></article>`).join(""); }
function renderTrend(rows) { const max=Math.max(1,...rows.map(x=>x.amount)); document.getElementById("trend-chart").innerHTML=rows.map(x=>`<div class="bar-group"><div class="bar-value">${yen(x.amount)}</div><div class="bar" style="height:${Math.max(4,x.amount/max*150)}px"></div><small>${x.date.slice(8)}日</small></div>`).join(""); }
function renderBreakdown(id, rows) { const total=rows.reduce((a,x)=>a+x.amount,0); const colors=["#3478e5","#66b58f","#f4b548","#e279a9","#a5b4c8"]; let cursor=0; const gradient=rows.map((x,i)=>{const start=cursor;cursor+=total?x.amount/total*360:0;return `${colors[i%colors.length]} ${start}deg ${cursor}deg`;}).join(","); document.getElementById(id).innerHTML=rows.length?`<div class="donut" style="background:conic-gradient(${gradient})"><span>${yen(total)}<small>合計</small></span></div><div class="legend">${rows.map((x,i)=>`<div><i style="background:${colors[i%colors.length]}"></i><span>${safe(x.label)}</span><b>${yen(x.amount)} (${Number(x.percentage||0).toFixed(1)}%)</b></div>`).join("")}</div>`:`<p class="empty">データなし</p>`; }
function table(id, headers, rows, empty) { document.getElementById(id).innerHTML=rows.length?`<div class="data-table"><div class="table-row table-head">${headers.map(x=>`<span>${x}</span>`).join("")}</div>${rows.map(row=>`<div class="table-row">${row.map(x=>`<span>${safe(x)}</span>`).join("")}</div>`).join("")}</div>`:`<p class="empty">${empty}</p>`; }
async function load() { const geminiApiKey=window.prompt("Dashboardの分析に使用するGemini APIキーを入力してください。\nAPIキーは保存されません。"); if(!geminiApiKey?.trim()){status.textContent="Gemini APIキーが入力されなかったため、分析を中止しました。";status.classList.add("error-message");return;} status.textContent="保存済みデータをGeminiで分析中です。"; try { const response=await fetch(`${API_BASE_URL}/api/dashboard/analyze`,{method:"POST",headers:{"Content-Type":"application/json; charset=UTF-8"},body:JSON.stringify({geminiApiKey:geminiApiKey.trim()})}); const d=await response.json().catch(()=>({})); if(!response.ok) throw new Error(d.message||`HTTP ${response.status}`); renderKpis(d);renderTrend(d.dailyTrend||[]);renderBreakdown("store-chart",d.storeBreakdown||[]);renderBreakdown("category-chart",d.categoryBreakdown||[]);table("recent-table",["日付","店舗名","カテゴリ","合計金額"],(d.recentReceipts||[]).map(x=>[x.purchasedAt?new Date(x.purchasedAt).toLocaleDateString("ja-JP"):"日時不明",x.storeName,x.storeCategory,yen(x.totalAmount)]),"今月の支出データはありません。");table("items-table",["商品名","カテゴリ","購入回数","合計金額"],(d.topItems||[]).map(x=>[x.itemName,x.category,`${x.purchaseCount}回`,yen(x.totalAmount)]),"商品データはありません。");status.textContent="Geminiによる分析が完了しました。";content.classList.remove("hidden"); } catch(e) { const detail=e?.name === "TypeError" ? `Backendに接続できません。Backendを起動し、${API_BASE_URL}/api/health が開けることを確認してください。` : e.message; status.textContent=`分析エラー: ${detail}`;status.classList.add("error-message"); } }
load();
