const API_BASE_URL = window.APP_CONFIG?.API_BASE_URL ?? "http://localhost:8081";
const localModeButton=document.getElementById("local-mode"), roomModeButton=document.getElementById("room-mode"), roomPanel=document.getElementById("room-panel"), roomCodeLabel=document.getElementById("room-code-label"), playerName=document.getElementById("player-name"), roomCode=document.getElementById("room-code"), createRoom=document.getElementById("create-room"), joinRoom=document.getElementById("join-room"), roomInfo=document.getElementById("room-info"), apiKey=document.getElementById("game-api-key"), clearKey=document.getElementById("clear-game-key"), filesInput=document.getElementById("game-files"), fileNames=document.getElementById("file-names"), uploadButton=document.getElementById("upload-files"), statusElement=document.getElementById("game-status"), candidateList=document.getElementById("candidate-list"), monsterPanel=document.getElementById("monster-panel"), lockButton=document.getElementById("lock-button"), nextPlayer=document.getElementById("next-player"), playerLabel=document.getElementById("player-label"), stepLabel=document.getElementById("step-label"), resultCard=document.getElementById("battle-result"), battleContent=document.getElementById("battle-content");
let mode="local", phase="PLAYER1", candidates=[], selected=null, busy=false, room=null, pollTimer=null, objectUrls=[];
const escapeHtml=value=>String(value??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
function setStatus(text,error=false){statusElement.textContent=text;statusElement.classList.toggle("error-message",error);}
function url(path){return `${API_BASE_URL}${path}`;}
async function request(path,options={}){const response=await fetch(url(path),options);let body=null;try{body=await response.json();}catch{}if(!response.ok){const e=new Error(body?.message||"通信に失敗しました。");e.code=body?.code;e.status=response.status;throw e;}return body;}
function headers(){return room?.token?{"X-Receipt-Game-Token":room.token}:{};}
function clearObjects(){objectUrls.forEach(URL.revokeObjectURL);objectUrls=[];}
function resetPlayer(){clearObjects();candidates=[];selected=null;candidateList.replaceChildren();monsterPanel.classList.add("hidden");monsterPanel.replaceChildren();lockButton.classList.add("hidden");nextPlayer.classList.add("hidden");resultCard.classList.add("hidden");filesInput.value="";fileNames.textContent="未選択";stepLabel.textContent="候補レシートをアップロード";setStatus("");}
function renderCandidates(){candidateList.innerHTML=candidates.map((c,i)=>`<article class="candidate-card"><div class="candidate-thumb" id="thumb-${i}">画像</div><dl><div><dt>店舗</dt><dd>${escapeHtml(c.storeName||"不明")}</dd></div><div><dt>購入日</dt><dd>${escapeHtml(c.purchasedAt||"不明")}</dd></div><div><dt>合計</dt><dd>${c.totalAmount==null?"不明":escapeHtml(c.totalAmount.toLocaleString())+"円"}</dd></div></dl><button data-index="${i}" type="button">このレシートを選ぶ</button></article>`).join("");candidateList.querySelectorAll("button").forEach(b=>b.addEventListener("click",()=>selectCandidate(Number(b.dataset.index))));candidates.forEach((c,i)=>{if(c.preview){const img=document.createElement("img");img.src=c.preview;img.alt="レシートサムネイル";document.getElementById(`thumb-${i}`).replaceChildren(img);}});}
async function selectCandidate(index){selected=candidates[index];candidateList.querySelectorAll("button").forEach(b=>b.disabled=true);setStatus("モンスターを生成中です。Geminiの応答を待っています。");try{const path=mode==="room"?`/api/receipt-game/rooms/${room.code}/monsters/${encodeURIComponent(selected.receiptTableName)}`:`/api/receipt-game/monsters/${encodeURIComponent(selected.receiptTableName)}`;selected.monster=await request(path,{method:"POST",headers:headers(),body:new URLSearchParams({geminiApiKey:apiKey.value})});renderMonster(selected.monster);setStatus("モンスターが準備できました。能力を確認してLOCKしてください。");}catch(e){setStatus(e.message,true);candidateList.querySelectorAll("button").forEach(b=>b.disabled=false);}}
function renderMonster(m){monsterPanel.classList.remove("hidden");monsterPanel.innerHTML=`<div class="monster-card"><div class="monster-image-wrap"><img id="monster-image" alt="${escapeHtml(m.monsterName)}"></div><div><p class="rarity">${escapeHtml(m.rarity)}</p><h3>${escapeHtml(m.monsterName)}</h3><p>${escapeHtml(m.species)}</p><div class="stat-bars"><span>POWER <b>${m.power}</b></span><span>GUARD <b>${m.guard}</b></span><span>SPEED <b>${m.speed}</b></span></div></div></div>`;const img=document.getElementById("monster-image");if(m.imageDataUrl) img.src=m.imageDataUrl; else if(mode==="room"){fetchImage(m.imageUrl,room.token).then(src=>img.src=src).catch(e=>setStatus(e.message,true));}lockButton.classList.remove("hidden");}
async function fetchImage(path,token){const r=await fetch(url(path),{headers:{"X-Receipt-Game-Token":token}});if(!r.ok)throw new Error("モンスター画像を取得できませんでした。");const src=URL.createObjectURL(await r.blob());objectUrls.push(src);return src;}
async function uploadFiles(){if(busy)return;const files=[...filesInput.files];if(files.length<1){setStatus("レシート画像を1枚以上選択してください。",true);return;}if(candidates.length+files.length>10){setStatus("1人あたり10枚まで選択できます。",true);return;}if(files.some(f=>f.size>5242880)){setStatus("5MBを超える画像は選択できません。",true);return;}busy=true;uploadButton.disabled=true;let success=0;for(const file of files){try{const data=new FormData();data.append("file",file);data.append("geminiApiKey",apiKey.value);const path=mode==="room"?`/api/receipt-game/rooms/${room.code}/candidates`:`/api/receipt-game/candidates`;const c=await request(path,{method:"POST",headers:headers(),body:data});if(!candidates.some(x=>x.imageSha256===c.imageSha256)){c.preview=URL.createObjectURL(file);objectUrls.push(c.preview);candidates.push(c);success++;}setStatus(`${success}/${files.length}枚を候補に追加しました。`);}catch(e){setStatus(`${success}/${files.length}枚成功。今回の画像は除外: ${e.message}`,true);}}busy=false;uploadButton.disabled=false;renderCandidates();if(candidates.length===0)setStatus("対戦に使用できるレシートがありません。別のレシート画像をアップロードしてください。",true);}
async function lock(){if(!selected?.monster||busy)return;busy=true;lockButton.disabled=true;try{if(mode==="room"){const state=await request(`/api/receipt-game/rooms/${room.code}/lock`,{method:"POST",headers:{...headers(),"Content-Type":"application/json"},body:JSON.stringify({monsterId:selected.monster.monsterId})});renderRoomState(state);setStatus(state.battle?"BATTLE COMPLETE":state.opponentLocked?"相手のLOCKを確認しました。":"LOCKしました。相手の選択を待っています。");startPolling();}else if(phase==="PLAYER1"){lockButton.classList.add("hidden");nextPlayer.classList.remove("hidden");stepLabel.textContent="Player 1 LOCK済み";setStatus("選択内容を非表示にしました。PLAYER 2へ交代してください。");apiKey.value="";}else{const battle=await request("/api/receipt-game/battles/local",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({player1MonsterId:window.p1MonsterId,player2MonsterId:selected.monster.monsterId})});showBattle(battle);}}catch(e){setStatus(e.message,true);lockButton.disabled=false;}busy=false;}
function next(){window.p1MonsterId=selected.monster.monsterId;phase="PLAYER2";playerLabel.textContent="PLAYER 2";resetPlayer();apiKey.value="";setStatus("Player 2のGemini APIキーを入力してください。");}
function showBattle(b){resultCard.classList.remove("hidden");battleContent.innerHTML=`<div class="battle-grid">${battleMonster(b.player1,b.player1BattleScoreX2/2,"PLAYER 1") }<div class="versus">VS<br><strong>${escapeHtml(b.winnerPlayer)} WINNER</strong></div>${battleMonster(b.player2,b.player2BattleScoreX2/2,"PLAYER 2")}</div>`;resultCard.scrollIntoView({behavior:"smooth"});}
function battleMonster(m,score,label){return `<article class="battle-monster"><p>${label}</p><img src="${m.imageDataUrl || ""}" alt="${escapeHtml(m.monsterName)}"><h3>${escapeHtml(m.monsterName)}</h3><p>${escapeHtml(m.rarity)} / ${escapeHtml(m.species)}</p><p>POWER ${m.power} / GUARD ${m.guard} / SPEED ${m.speed}</p><strong>BATTLE SCORE ${score}</strong></article>`;}
function renderRoomState(state){playerLabel.textContent=state.player;roomInfo.textContent=`ROOM CODE: ${state.roomCode}　状態: ${state.status}`;if(state.ownMonster){selected={monster:state.ownMonster};renderMonster(state.ownMonster);lockButton.classList.toggle("hidden",state.ownLocked);}if(state.battle)showBattleWithRoom(state.battle);}
function showBattleWithRoom(b){resultCard.classList.remove("hidden");const p1=b.player1,p2=b.player2;battleContent.innerHTML=`<div class="battle-grid"><article class="battle-monster"><p>PLAYER 1</p><img data-room-image="${p1.monsterId}" alt="${escapeHtml(p1.monsterName)}"><h3>${escapeHtml(p1.monsterName)}</h3><p>${p1.rarity} / ${p1.species}</p><p>POWER ${p1.power} / GUARD ${p1.guard} / SPEED ${p1.speed}</p><strong>BATTLE SCORE ${b.player1BattleScoreX2/2}</strong></article><div class="versus">VS<br><strong>${escapeHtml(b.winnerPlayer)} WINNER</strong></div><article class="battle-monster"><p>PLAYER 2</p><img data-room-image="${p2.monsterId}" alt="${escapeHtml(p2.monsterName)}"><h3>${escapeHtml(p2.monsterName)}</h3><p>${p2.rarity} / ${p2.species}</p><p>POWER ${p2.power} / GUARD ${p2.guard} / SPEED ${p2.speed}</p><strong>BATTLE SCORE ${b.player2BattleScoreX2/2}</strong></article></div>`;document.querySelectorAll("[data-room-image]").forEach(async img=>{try{img.src=await fetchImage(`/api/receipt-game/rooms/${room.code}/monsters/${img.dataset.roomImage}/image`,room.token);}catch{}});resultCard.scrollIntoView({behavior:"smooth"});}
function startPolling(){if(mode!=="room"||pollTimer)return;pollTimer=setInterval(async()=>{try{const state=await request(`/api/receipt-game/rooms/${room.code}`,{headers:headers()});renderRoomState(state);if(state.status==="BATTLE_COMPLETE")clearInterval(pollTimer),pollTimer=null;}catch(e){setStatus(e.message,true);}},3000);}
function switchMode(nextMode){mode=nextMode;localModeButton.classList.toggle("active",mode==="local");roomModeButton.classList.toggle("active",mode==="room");roomPanel.classList.toggle("hidden",mode!=="room");roomCodeLabel.classList.toggle("hidden",mode!=="room");resetPlayer();playerLabel.textContent="PLAYER 1";phase="PLAYER1";room=null;roomInfo.textContent="";if(pollTimer)clearInterval(pollTimer),pollTimer=null;}
localModeButton.addEventListener("click",()=>switchMode("local"));roomModeButton.addEventListener("click",()=>switchMode("room"));clearKey.addEventListener("click",()=>{apiKey.value="";apiKey.focus();});filesInput.addEventListener("change",()=>{const files=[...filesInput.files];fileNames.textContent=files.length?files.map(f=>f.name).join("、"):"未選択";});uploadButton.addEventListener("click",uploadFiles);lockButton.addEventListener("click",lock);nextPlayer.addEventListener("click",next);createRoom.addEventListener("click",async()=>{try{room=await request("/api/receipt-game/rooms",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({playerName:playerName.value})});roomInfo.textContent=`ROOM CODE: ${room.roomCode}（このコードと参加用画面を相手へ共有）`;setStatus("ルームを作成しました。候補をアップロードしてください。");}catch(e){setStatus(e.message,true);}});joinRoom.addEventListener("click",async()=>{try{room=await request(`/api/receipt-game/rooms/${roomCode.value.trim().toUpperCase()}/join`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({playerName:playerName.value})});roomInfo.textContent=`ROOM CODE: ${room.roomCode} に参加しました。`;setStatus("候補をアップロードしてください。");}catch(e){setStatus(e.message,true);}});
