package com.example.receipt.service;

import com.example.receipt.dto.MonsterCard;
import com.example.receipt.exception.ReceiptException;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.SecureRandom;
import java.time.Instant;
import java.util.*;

@Service
public class RemoteGameService {
    private final JdbcTemplate db; private final SvgCardService cards; private final boolean secure; private final SecureRandom random=new SecureRandom();
    public RemoteGameService(JdbcTemplate db,SvgCardService cards,@Value("${app.auth.cookie-secure:true}") boolean secure){this.db=db;this.cards=cards;this.secure=secure;}
    private void init(){db.execute("CREATE TABLE IF NOT EXISTS receipt_game_room (room_code CHAR(8) PRIMARY KEY, state VARCHAR(16) NOT NULL, p1_token CHAR(64) NOT NULL, p2_token CHAR(64), p1_receipt VARCHAR(64), p1_seed CHAR(64), p2_receipt VARCHAR(64), p2_seed CHAR(64), score1 INTEGER, score2 INTEGER, winner VARCHAR(64), created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, last_action_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, expires_at TIMESTAMPTZ NOT NULL)");db.execute("ALTER TABLE receipt_game_room ADD COLUMN IF NOT EXISTS p1_session_hash CHAR(64)");db.execute("ALTER TABLE receipt_game_room ADD COLUMN IF NOT EXISTS p2_session_hash CHAR(64)");db.update("DELETE FROM receipt_game_room WHERE expires_at<=CURRENT_TIMESTAMP OR created_at<CURRENT_TIMESTAMP-INTERVAL '120 minutes'");}
    public synchronized Created create(String sessionId){init();if(db.queryForObject("SELECT COUNT(*) FROM receipt_game_room WHERE expires_at>CURRENT_TIMESTAMP AND state='OPEN' AND (p1_session_hash=? OR p2_session_hash=?)",Integer.class,hash(sessionId),hash(sessionId))>0)throw conflict();String code,token;do{code=code();}while(db.queryForList("SELECT room_code FROM receipt_game_room WHERE room_code=?",String.class,code).size()>0);token=token();db.update("INSERT INTO receipt_game_room(room_code,state,p1_token,p1_session_hash,expires_at) VALUES(?,'OPEN',?,?,CURRENT_TIMESTAMP+INTERVAL '60 minutes')",code,hash(token),hash(sessionId));return new Created(code,token);}
    public synchronized String join(String code,String sessionId){init();String token=token();int n=db.update("UPDATE receipt_game_room SET p2_token=?,p2_session_hash=?,last_action_at=CURRENT_TIMESTAMP,expires_at=LEAST(created_at+INTERVAL '120 minutes',CURRENT_TIMESTAMP+INTERVAL '60 minutes') WHERE room_code=? AND state='OPEN' AND p2_token IS NULL AND p1_session_hash<>? AND expires_at>CURRENT_TIMESTAMP",hash(token),hash(sessionId),code,hash(sessionId));if(n!=1)throw missing();return token;}
    @Transactional public Map<String,Object> state(String code,String token){init();var rows=db.query("SELECT state,p1_token,p2_token,p1_receipt,p1_seed,p2_receipt,p2_seed,score1,score2,winner FROM receipt_game_room WHERE room_code=? AND expires_at>CURRENT_TIMESTAMP FOR UPDATE",(r,n)->new Object[]{r.getString(1),r.getString(2),r.getString(3),r.getString(4),r.getString(5),r.getString(6),r.getString(7),r.getObject(8),r.getObject(9),r.getString(10)},code);if(rows.isEmpty())throw missing();Object[] x=rows.getFirst();int seat=seat(x,token);Map<String,Object> out=new LinkedHashMap<>();out.put("state",x[0]);out.put("opponentJoined",x[2]!=null);out.put("player1Confirmed",x[3]!=null);out.put("player2Confirmed",x[5]!=null);out.put("myConfirmed",seat==1?x[3]!=null:x[5]!=null);if("DONE".equals(x[0])){MonsterCard a=cards.get((String)x[3]),b=cards.get((String)x[5]);out.put("player1",a);out.put("player2",b);out.put("scoreX2Player1",x[7]);out.put("scoreX2Player2",x[8]);out.put("scorePlayer1",((Number)x[7]).doubleValue()/2);out.put("scorePlayer2",((Number)x[8]).doubleValue()/2);out.put("winner",x[9]);}if(seat<1)throw missing();return out;}
    @Transactional public Map<String,Object> select(String code,String token,String receipt){init();var rows=db.query("SELECT state,p1_token,p2_token,p1_receipt,p1_seed,p2_receipt,p2_seed FROM receipt_game_room WHERE room_code=? AND expires_at>CURRENT_TIMESTAMP FOR UPDATE",(r,n)->new Object[]{r.getString(1),r.getString(2),r.getString(3),r.getString(4),r.getString(5),r.getString(6),r.getString(7)},code);if(rows.isEmpty())throw missing();Object[] x=rows.getFirst();int seat=seat(x,token);if(!"OPEN".equals(x[0]))throw conflict();MonsterCard card=cards.get(receipt);if(seat==1){if(x[3]!=null)throw conflict();db.update("UPDATE receipt_game_room SET p1_receipt=?,p1_seed=?,last_action_at=CURRENT_TIMESTAMP,expires_at=LEAST(created_at+INTERVAL '120 minutes',CURRENT_TIMESTAMP+INTERVAL '60 minutes') WHERE room_code=?",receipt,card.seed(),code);}else{if(x[5]!=null)throw conflict();db.update("UPDATE receipt_game_room SET p2_receipt=?,p2_seed=?,last_action_at=CURRENT_TIMESTAMP,expires_at=LEAST(created_at+INTERVAL '120 minutes',CURRENT_TIMESTAMP+INTERVAL '60 minutes') WHERE room_code=?",receipt,card.seed(),code);}
        Object[] both=db.queryForObject("SELECT p1_receipt,p1_seed,p2_receipt,p2_seed FROM receipt_game_room WHERE room_code=?",(r,n)->new Object[]{r.getString(1),r.getString(2),r.getString(3),r.getString(4)},code);if(both[0]!=null&&both[2]!=null){if(both[0].equals(both[2])){db.update("UPDATE receipt_game_room SET state='INVALID' WHERE room_code=?",code);return Map.of("confirmed",true,"resultReady",false,"sameReceipt",true);}MonsterCard a=cards.get((String)both[0]),b=cards.get((String)both[2]);if(!a.seed().equals(both[1])||!b.seed().equals(both[3]))throw conflict();int sa=score(a,b),sb=score(b,a);String winner=sa==sb?((a.seed()+a.receiptId()).compareTo(b.seed()+b.receiptId())>0?a.receiptId():b.receiptId()):sa>sb?a.receiptId():b.receiptId();db.update("UPDATE receipt_game_room SET state='DONE',score1=?,score2=?,winner=? WHERE room_code=?",sa,sb,winner,code);}return Map.of("confirmed",true,"resultReady",both[0]!=null&&both[2]!=null);}
    public void cancel(String code,String token){init();var row=db.query("SELECT p1_token,p2_token FROM receipt_game_room WHERE room_code=? AND expires_at>CURRENT_TIMESTAMP",(r,n)->new String[]{r.getString(1),r.getString(2)},code);if(row.isEmpty())throw missing();seat(new Object[]{null,row.getFirst()[0],row.getFirst()[1]},token);db.update("UPDATE receipt_game_room SET state='CANCELLED',p1_token=?,p2_token=NULL WHERE room_code=?",hash(token()),code);}
    private int seat(Object[] x,String t){String h=hash(t);if(MessageDigest.isEqual(h.getBytes(StandardCharsets.UTF_8),((String)x[1]).getBytes(StandardCharsets.UTF_8)))return 1;if(x[2]!=null&&MessageDigest.isEqual(h.getBytes(StandardCharsets.UTF_8),((String)x[2]).getBytes(StandardCharsets.UTF_8)))return 2;throw missing();}
    private int score(MonsterCard a,MonsterCard b){return BattleScoring.scoreX2(a,b);}
    private String code(){String alphabet="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";StringBuilder b=new StringBuilder();for(int i=0;i<8;i++)b.append(alphabet.charAt(random.nextInt(alphabet.length())));return b.toString();}
    private String token(){byte[] b=new byte[32];random.nextBytes(b);return HexFormat.of().formatHex(b);}
    private String hash(String s){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
    private ReceiptException missing(){return new ReceiptException(HttpStatus.NOT_FOUND,"ROOM_UNAVAILABLE","ルームが見つからないか、期限切れです。新しいルームを作成してください。");} private ReceiptException conflict(){return new ReceiptException(HttpStatus.CONFLICT,"ROOM_STATE_INVALID","ルーム状態が更新されています。状態を再取得してください。");}
    public boolean secureCookie(){return secure;} public record Created(String code,String token){}
}
