package com.example.receipt.repository;

import com.example.receipt.exception.ReceiptException;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.BatchPreparedStatementSetter;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.List;

@Repository
public class ReceiptTableRepository {
    private final JdbcTemplate jdbcTemplate;

    public ReceiptTableRepository(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    public String createReceiptTableAndInsert(List<String> lines) {
        String tableName = ReceiptTableName.generate();
        assertSafeTableName(tableName);

        String createSql = """
                CREATE TABLE %s (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    line_no INTEGER NOT NULL,
                    text TEXT NOT NULL,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """.formatted(tableName);

        jdbcTemplate.execute(createSql);

        String insertSql = "INSERT INTO " + tableName + " (line_no, text) VALUES (?, ?)";
        jdbcTemplate.batchUpdate(insertSql, new BatchPreparedStatementSetter() {
            @Override
            public void setValues(PreparedStatement ps, int i) throws SQLException {
                ps.setInt(1, i + 1);
                ps.setString(2, lines.get(i));
            }

            @Override
            public int getBatchSize() {
                return lines.size();
            }
        });

        return tableName;
    }

    static void assertSafeTableName(String tableName) {
        if (!ReceiptTableName.isSafe(tableName)) {
            throw new ReceiptException(HttpStatus.INTERNAL_SERVER_ERROR, "UNSAFE_TABLE_NAME", "安全でないテーブル名が生成されました。");
        }
    }
}
