package com.example.receipt.repository;

import com.example.receipt.dto.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;
import java.sql.Timestamp;
import java.time.*;
import java.util.*;

@Repository
public class ReceiptAnalyticsRepository {
    private static final String SUMMARY = "receipt_structured_summary";
    private final JdbcTemplate jdbc;
    public ReceiptAnalyticsRepository(JdbcTemplate jdbc) { this.jdbc = jdbc; }

    public void ensureTables() {
        jdbc.execute("CREATE TABLE IF NOT EXISTS receipt_image_hash_registry (image_sha256 VARCHAR(64) PRIMARY KEY, table_name VARCHAR(64) UNIQUE, created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP)");
        jdbc.execute("""
                CREATE TABLE IF NOT EXISTS receipt_structured_summary (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, receipt_table_name VARCHAR(64) NOT NULL UNIQUE,
            image_sha256 VARCHAR(64) NOT NULL UNIQUE, store_name VARCHAR(255), branch_name VARCHAR(255),
            store_category VARCHAR(50), purchased_at TIMESTAMP, total_amount BIGINT, payment_method VARCHAR(100),
            receipt_number VARCHAR(100), created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP)
                """);
        jdbc.execute("""
                CREATE TABLE IF NOT EXISTS receipt_structured_item (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, receipt_table_name VARCHAR(64) NOT NULL,
            item_no INTEGER NOT NULL, item_name TEXT NOT NULL, category VARCHAR(50) NOT NULL, quantity NUMERIC(12,3),
            unit_price BIGINT, amount BIGINT, created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE (receipt_table_name, item_no))
                """);
        jdbc.execute("CREATE INDEX IF NOT EXISTS idx_structured_purchased_at ON receipt_structured_summary(purchased_at)");
    }

    public void save(String table, String sha, ReceiptStructuredData data) {
        ensureTables();
        if (data == null) data = new ReceiptStructuredData(null, null, "その他", null, null, null, null, List.of());
        jdbc.update("INSERT INTO receipt_structured_summary (receipt_table_name,image_sha256,store_name,branch_name,store_category,purchased_at,total_amount,payment_method,receipt_number) VALUES (?,?,?,?,?,?,?,?,?)",
                table, sha, data.storeName(), data.branchName(), data.storeCategory(), data.purchasedAt(), data.totalAmount(), data.paymentMethod(), data.receiptNumber());
        List<ReceiptItemData> items = data.safeItems();
        for (int i = 0; i < items.size(); i++) {
            ReceiptItemData item = items.get(i);
            if (item == null || item.name() == null || item.name().isBlank()) continue;
            jdbc.update("INSERT INTO receipt_structured_item (receipt_table_name,item_no,item_name,category,quantity,unit_price,amount) VALUES (?,?,?,?,?,?,?)",
                    table, i + 1, item.name(), item.category() == null ? "その他" : item.category(), item.quantity(), item.unitPrice(), item.amount());
        }
    }

    public DashboardResponse dashboard() {
        ensureTables();
        ZoneId zone = ZoneId.of("Asia/Tokyo"); LocalDate today = LocalDate.now(zone); YearMonth current = YearMonth.from(today);
        LocalDateTime start = current.atDay(1).atStartOfDay(), end = current.plusMonths(1).atDay(1).atStartOfDay();
        Long total = jdbc.queryForObject("SELECT COALESCE(SUM(total_amount),0) FROM " + SUMMARY + " WHERE purchased_at >= ? AND purchased_at < ?", Long.class, start, end);
        Long count = jdbc.queryForObject("SELECT COUNT(*) FROM " + SUMMARY + " WHERE purchased_at >= ? AND purchased_at < ?", Long.class, start, end);
        Long all = jdbc.queryForObject("SELECT COUNT(*) FROM receipt_image_hash_registry WHERE table_name IS NOT NULL", Long.class);
        List<DashboardDailyTrend> trend = new ArrayList<>();
        for (int day = 1; day <= today.getDayOfMonth(); day++) {
            LocalDate date = current.atDay(day);
            Long amount = jdbc.queryForObject("SELECT COALESCE(SUM(total_amount),0) FROM " + SUMMARY + " WHERE purchased_at >= ? AND purchased_at < ?", Long.class, date.atStartOfDay(), date.plusDays(1).atStartOfDay());
            trend.add(new DashboardDailyTrend(date.toString(), amount == null ? 0 : amount));
        }
        return new DashboardResponse(current.toString(), total == null ? 0 : total, count == null ? 0 : count, (total == null ? 0 : total) / today.getDayOfMonth(), all == null ? 0 : all,
                trend, breakdown("store_category", start, end), categoryBreakdown(start, end), recent(), topItems(start, end));
    }
    private List<DashboardBreakdown> breakdown(String column, LocalDateTime start, LocalDateTime end) {
        List<Map<String,Object>> rows = jdbc.queryForList("SELECT COALESCE(" + column + ",'その他') label, COALESCE(SUM(total_amount),0) amount FROM " + SUMMARY + " WHERE purchased_at >= ? AND purchased_at < ? AND total_amount IS NOT NULL GROUP BY " + column + " ORDER BY amount DESC", start, end);
        long sum = rows.stream().mapToLong(r -> ((Number)r.get("amount")).longValue()).sum(); return rows.stream().map(r -> new DashboardBreakdown(String.valueOf(r.get("label")), ((Number)r.get("amount")).longValue(), sum == 0 ? 0 : ((Number)r.get("amount")).doubleValue() * 100 / sum)).toList();
    }
    private List<DashboardBreakdown> categoryBreakdown(LocalDateTime start, LocalDateTime end) { String sql = "SELECT COALESCE(i.category,'その他') label, COALESCE(SUM(i.amount),0) amount FROM receipt_structured_item i JOIN " + SUMMARY + " s ON s.receipt_table_name=i.receipt_table_name WHERE s.purchased_at >= ? AND s.purchased_at < ? GROUP BY i.category ORDER BY amount DESC"; List<Map<String,Object>> rows=jdbc.queryForList(sql,start,end); long sum=rows.stream().mapToLong(r->((Number)r.get("amount")).longValue()).sum(); return rows.stream().map(r->new DashboardBreakdown(String.valueOf(r.get("label")),((Number)r.get("amount")).longValue(),sum==0?0:((Number)r.get("amount")).doubleValue()*100/sum)).toList(); }
    private List<DashboardRecentReceipt> recent() { return jdbc.query("SELECT receipt_table_name,purchased_at,store_name,store_category,total_amount FROM " + SUMMARY + " WHERE purchased_at IS NOT NULL ORDER BY purchased_at DESC LIMIT 5", (rs,n)-> { Number amount = (Number) rs.getObject(5); return new DashboardRecentReceipt(rs.getString(1), rs.getObject(2, LocalDateTime.class), rs.getString(3), rs.getString(4), amount == null ? null : amount.longValue()); }); }
    private List<DashboardTopItem> topItems(LocalDateTime start, LocalDateTime end) { return jdbc.query("SELECT i.item_name,i.category,COUNT(*) purchase_count,COALESCE(SUM(i.amount),0) total_amount FROM receipt_structured_item i JOIN " + SUMMARY + " s ON s.receipt_table_name=i.receipt_table_name WHERE s.purchased_at >= ? AND s.purchased_at < ? GROUP BY i.item_name,i.category ORDER BY total_amount DESC LIMIT 5", (rs,n)->new DashboardTopItem(rs.getString(1),rs.getString(2),rs.getLong(3),rs.getLong(4)),start,end); }
}
